
#pragma once

#include <taglib/taglib.h>

#if (TAGLIB_MAJOR_VERSION >= 2)
    #define LMS_TAGLIB_HAS_DSF 1
    #define LMS_TAGLIB_HAS_ADTS 1
#endif

// LMS_TAGLIB_HAS_MP4_ITEM_TYPE if version >= 2.0.1
#if ((TAGLIB_MAJOR_VERSION > 2) || (TAGLIB_MAJOR_VERSION == 2 && TAGLIB_MINOR_VERSION > 0) || (TAGLIB_MAJOR_VERSION == 2 && TAGLIB_PATCH_VERSION >= 1))
    #define LMS_TAGLIB_HAS_MP4_ITEM_TYPE 1
#endif

// LMS_TAGLIB_HAS_APE_COMPLEX_PROPERTIES if version >= 2.0.2
#if ((TAGLIB_MAJOR_VERSION > 2) || (TAGLIB_MAJOR_VERSION == 2 && TAGLIB_MINOR_VERSION > 0) || (TAGLIB_MAJOR_VERSION == 2 && TAGLIB_PATCH_VERSION >= 2))
    #define LMS_TAGLIB_HAS_APE_COMPLEX_PROPERTIES 1
#endif

// LMS_TAGLIB_HAS_SHORTEN if version >= 2.1
#if ((TAGLIB_MAJOR_VERSION > 2) || (TAGLIB_MAJOR_VERSION == 2 && TAGLIB_MINOR_VERSION >= 1))
    #define LMS_TAGLIB_HAS_SHORTEN 1
#endif
